/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125428-g1836ef9684-20260702"
#endif /* AVUTIL_FFVERSION_H */
